### ISSUE TITLE
Always requires import

### ISSUE THREAD

**Issue by wdonne** [fuchsst/jslt-intellij-plugin#1]
Hello,

The plugin always complains about not seeing an import statement when the file begins with a curly brace. Just take the very first example of the language tutorial to reproduce this. I'm using version 1.0.2.

Best regards,

Werner.

**Comment by fuchsst** [comment]
Hi,

thanks for reporting!
Update with fix is in review and should be available soon on the Jetbrains marketplace...

BR, Stefan
