### ISSUE TITLE
Incompatible with latest version of IntelliJ

### ISSUE THREAD

**Issue by oreid-zd** [fuchsst/jslt-intellij-plugin#2]
Hey,

As the title suggests, this plugin is incompatible with the latest version of IntelliJ.

![image](https://user-images.githubusercontent.com/88991030/207467505-1a91cd09-6712-474d-ba38-786dfad17de4.png)

Thanks!

**Comment by fuchsst** [comment]
thanks for reporting!
pushed an update...should be available in the next days as soon as it went through JetBrain's validation

**Comment by oreid-zd** [comment]
Hey, I see that this occurred again but you beat me to it this time. If you provide an example of the sort of update I need to make/any other things to do, I can assist you in creating PRs to update this plugin when IntelliJ updates (if you'd appreciate that)?
