### ISSUE TITLE
Incompatible with IntelliJ IDEA 2023.1 (Community Edition)

### ISSUE THREAD

**Issue by adamstruck** [fuchsst/jslt-intellij-plugin#4]
IntelliJ IDEA 2023.1 (Community Edition)
Build #IC-231.8109.175, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1

![image](https://user-images.githubusercontent.com/5560701/228909102-01debb49-9922-4ad5-b99a-beadf6b743cd.png)

**Comment by fuchsst** [comment]
Thanks for reporting!
