### ISSUE TITLE
JSLT object indentation style format is hard to read for long property names

### ISSUE THREAD

**Issue by DrGrognon** [fuchsst/jslt-intellij-plugin#6]
First of all thanks a lot for maintaining this plugin 🥰

I'm encoutering an issue with the default formatting of JSLT nested object expression. Indeed it align properties based on the position of the opening brace of the object. 
This lead to really unpleasant indent in situation of long properties names:
![image](https://github.com/fuchsst/jslt-intellij-plugin/assets/46163392/c3760389-6a6e-47e0-9521-593b984c4600)

While this can be worked around using Allman style, this look a bit cumbersome as K&R indent style is a defacto  standard in json world and look quite well in this situation (expected): 
![image](https://github.com/fuchsst/jslt-intellij-plugin/assets/46163392/424dd82f-b830-4bec-b887-df3f2c6a7dcf)

Could you please consider support this indent style as a format option.
(I'm really not used to Intellij plugin dev but i can try to do it if you provide some clue on where to look in code and how to test)

Thanks in advance and kudo for you for the plugin <3

**Comment by LambertSpot** [comment]
My removing the creation of Alignment in the code, we were able to fix this crazy indentation. Created a PR for it, but you can see the change and do it yourself if you want. 

Link to PR: https://github.com/fuchsst/jslt-intellij-plugin/pull/7

**Comment by DrGrognon** [comment]
Wokr like a charm with last update :grinning:  Thanks a lot :pray:
